from __future__ import annotations

import json
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

from sage.builders.base import BuildResult
from sage.config import Config
from sage.domain import ExecutionResult, Outcome, sha256_file
from sage.einsums.domain import TensorCase
from sage.einsums.inventory import coverage, inventory
from sage.einsums.library_domain import OPERATIONS, LibraryCase, bootstrap_seeds
from sage.einsums.runtime import EinsumsRun
from sage.provenance import write_json
from sage.targets.einsums import EINSUMS_COMMIT, EinsumsTargetAdapter


class EinsumsLibraryRun(EinsumsRun):
    POLICY_VERSION = "einsums-library-1.0"
    OPERATIONS = OPERATIONS
    CASE_TYPE = LibraryCase
    FIXTURE_DIR = "fixtures/einsums-library"
    BUILD_FILES = (*EinsumsRun.BUILD_FILES, "input_harness.c")
    INSTRUMENTATION = "einsums-symsan-input-harness"
    LIMITATIONS = [
        "Requested scope: all CPU and Python APIs. HIP/GPU backends are excluded by user scope.",
        "Whole-library compatibility is unverified. Bounded API probes do not complete a module.",
        "Current probes cover rank-two f64 CPU tensors, selected linear algebra and complex FFT.",
        "Every validation input is newly generated by SymSan; bootstrap seeds are never evidence.",
        "Python replays 18 probes through owned f64 Tensor objects and 5 through the campaign ABI. "
        "This does not establish full pyeinsums API or lifetime compatibility.",
        "SymSan instruments input decoding only. All Einsums C++ code is a native boundary; "
        "this campaign does not explore library-internal branches. Pointer tracing is disabled.",
        "QR probe uses square positive-definite matrices; rectangular upstream q() is excluded.",
        "See library-coverage.json and source/inventory.json for missing CPU/Python surface.",
    ]

    @staticmethod
    def seeds() -> list[TensorCase]:
        return list(bootstrap_seeds())

    def translate(self) -> Path:
        if self.config.provider.name != "offline":
            raise ValueError(
                "Full-library model translation requires a multi-file provider; "
                "the single-file OpenAI tensor provider is not applicable"
            )
        destination = self.root / ".sage/upstreams/einsums" / EINSUMS_COMMIT
        if not (destination / "checkout").exists():
            raise ValueError(
                "prepare Einsums source first with sage target prepare --target einsums"
            )
        EinsumsTargetAdapter().prepare(self.config, destination)
        self.source_inventory = inventory(destination / "checkout")
        write_json(self.run_dir / "source/inventory.json", self.source_inventory)
        shutil.copytree(
            destination / "checkout",
            self.run_dir / "source/upstream",
            ignore=shutil.ignore_patterns(".git"),
        )
        shutil.copy2(
            destination / "checkout/LICENSE.txt", self.run_dir / "source/EINSUMS-LICENSE.txt"
        )
        candidate = self.run_dir / "translation/einsums-rs"
        shutil.copytree(
            self.root / "ports/einsums-rs",
            candidate,
            ignore=shutil.ignore_patterns("target", "__pycache__"),
        )
        hashes = {
            str(p.relative_to(candidate)): sha256_file(p)
            for p in candidate.rglob("*")
            if p.is_file()
        }
        self.manifest.translation_provider = {
            "name": "offline",
            "metadata": {
                "scope": "cpu-python-library",
                "implementation": "independent Rust crate",
                "complete": False,
                "source_commit": EINSUMS_COMMIT,
                "file_hashes": hashes,
            },
        }
        write_json(self.run_dir / "translation/metadata.json", self.manifest.translation_provider)
        self._save()
        return candidate

    def _build_rust(self, candidate: Path) -> BuildResult:
        build = self.run_dir / "builds/rust"
        build.mkdir()
        command = [
            "cargo",
            "build",
            "--release",
            "--locked",
            "--offline",
            "--manifest-path",
            str(candidate / "Cargo.toml"),
            "--target-dir",
            str(build / "target"),
        ]
        log = build / "build.log"
        success = self._command(command, log)
        binary = build / "target/release/einsums-candidate"
        self.python_library = (
            build
            / "target/release"
            / ("libsage_einsums.dylib" if sys.platform == "darwin" else "libsage_einsums.so")
        )
        success = success and binary.is_file() and self.python_library.is_file()
        return BuildResult(
            "einsums-rust-library",
            success,
            binary if success else None,
            command,
            log,
            {
                "binary_sha256": sha256_file(binary) if success else None,
                "python_library": str(self.python_library),
                "library_sha256": sha256_file(self.python_library) if success else None,
            },
        )

    def _execute(self, case: TensorCase, input_path: Path) -> Any:
        executions, comparison = super()._execute(case, input_path)
        runner = self.run_dir / "translation/einsums-rs/python/run_case.py"
        try:
            completed = subprocess.run(
                [sys.executable, str(runner), str(self.python_library), str(input_path)],
                capture_output=True,
                text=True,
                timeout=self.config.execution.timeout_seconds,
                check=False,
            )
            output = json.loads(completed.stdout) if completed.returncode == 0 else None
            result = ExecutionResult(
                "1.0",
                "python-rust-abi",
                case.case_id,
                completed.returncode,
                0,
                False,
                completed.stdout,
                completed.stderr,
                output,
                {"python_entrypoint": "Tensor API" if case.payload[0] < 18 else "campaign ABI"},
            )
        except (OSError, ValueError, subprocess.TimeoutExpired) as exc:
            result = ExecutionResult(
                "1.0",
                "python-rust-abi",
                case.case_id,
                70,
                0,
                isinstance(exc, subprocess.TimeoutExpired),
                "",
                str(exc),
                None,
                {},
            )
        executions.append(result)
        if comparison.outcome == Outcome.PASS:
            comparison = self.policy.compare(case, executions[0], result)
        return executions, comparison

    def _finish(self, comparisons: list[dict[str, Any]]) -> Path:
        source = getattr(self, "source_inventory", None)
        if source is not None:
            report = coverage(
                source,
                self.manifest.concolic_outcome.get("operations", {}),
                self.manifest.outcome_counts,
                target_language=self.CANDIDATE_LABEL,
            )
            write_json(self.run_dir / "library-coverage.json", report)
            if self.manifest.status == "COMPLETED":
                self.manifest.status = report["scope_status"]
            self.manifest.concolic_outcome["library_coverage"] = report
        return super()._finish(comparisons)


def create_run(config: Config, root: Path, **kwargs: Any) -> EinsumsRun:
    if config.provider.target_language == "cpp20":
        from sage.einsums.cpp_library_runtime import EinsumsCppLibraryRun
        from sage.einsums.cpp_runtime import EinsumsCppRun

        if config.equivalence.policy_version == "einsums-library-1.0":
            return EinsumsCppLibraryRun(config, root, **kwargs)
        if config.equivalence.policy_version != "einsums-tensor-1.0":
            raise ValueError("modern C++ requires the tensor or library policy")
        return EinsumsCppRun(config, root, **kwargs)
    if config.provider.target_language != "rust":
        raise ValueError(f"unsupported target language: {config.provider.target_language}")
    runtime = (
        EinsumsLibraryRun
        if config.equivalence.policy_version == "einsums-library-1.0"
        else EinsumsRun
    )
    return runtime(config, root, **kwargs)
