from __future__ import annotations

import collections
import contextlib
import json
import shutil
import subprocess
import time
import uuid
from dataclasses import replace
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, cast

from sage.builders.rust_candidate import RustCandidateBuilder
from sage.config import Config, dump_config
from sage.domain import (
    ComparisonResult,
    ExecutionResult,
    Outcome,
    RunManifest,
    TranslationRequest,
    TranslationResult,
    TranslationUnit,
    jsonable,
    sha256_bytes,
    sha256_file,
)
from sage.einsums.domain import OPERATIONS, TensorCase, bootstrap_seeds
from sage.einsums.policy import TensorPolicy
from sage.generators.symsan import SymSanGenerator
from sage.provenance import (
    append_jsonl,
    environment_record,
    record_event,
    utc_now,
    write_json,
)
from sage.reporting.html import write_html
from sage.reporting.markdown import render_markdown
from sage.runners.sandbox import SandboxedRunner
from sage.summarizers.offline import OfflineSummarizer
from sage.targets.einsums import EINSUMS_COMMIT, EinsumsTargetAdapter
from sage.translators.openai_provider import OpenAITranslationProvider

SOURCE_FILES = (
    "libs/Einsums/Tensor/include/Einsums/Tensor/Tensor.hpp",
    "libs/Einsums/TensorAlgebra/include/Einsums/TensorAlgebra/Permute.hpp",
    "libs/Einsums/TensorAlgebra/include/Einsums/TensorAlgebra/TensorAlgebra.hpp",
    "libs/Einsums/TensorAlgebra/include/Einsums/TensorAlgebra/Backends/GenericAlgorithm.hpp",
)
LIMITATIONS = [
    "Staged CPU tensor contract only: copy/indexing, add, elementwise multiply, "
    "transpose, matmul, scale.",
    "Rank two, contiguous row-major f64, dimensions 1..4; signed int8 input values scaled by 1/8.",
    "SymSan instruments the harness and instantiated Einsums templates; out-of-line "
    "C++/BLAS/OpenMP dependencies remain native.",
    "Bootstrap seeds are solver inputs only. All validation cases must be new "
    "SymSan-generated bytes.",
    "Views, arbitrary ranks/dtypes, decompositions, I/O, FFT, Python bindings, GPU and "
    "downstream Psi4 are outside this stage.",
    "Pointer-bounds tracing is disabled at native ABI boundaries; "
    "branch generation remains enabled.",
    "Passing cases establish sampled behavior only, not whole-library equivalence or a proof.",
]


class EinsumsRun:
    CANDIDATE_NAME = "einsums-rust"
    CANDIDATE_BUILD_KEY = "rust_candidate"
    CANDIDATE_LABEL = "rust"
    POLICY_VERSION = "einsums-tensor-1.0"
    OPERATIONS: tuple[str, ...] = OPERATIONS
    CASE_TYPE = TensorCase
    FIXTURE_DIR = "fixtures/einsums"
    LIMITATIONS = LIMITATIONS
    BUILD_FILES: tuple[str, ...] = ("driver.cpp", "CMakeLists.txt", "build_symsan.py")
    INSTRUMENTATION = "einsums-symsan-templates"

    @staticmethod
    def seeds() -> list[TensorCase]:
        return bootstrap_seeds()

    def __init__(
        self,
        config: Config,
        root: Path,
        *,
        provider_name: str | None = None,
        seed: int | None = None,
        run_mode: str = "platform-demo",
        selection: Any | None = None,
    ) -> None:
        if config.target is None or config.target.name != "einsums":
            raise ValueError("Einsums runtime requires an Einsums configuration")
        if config.target.upstream_commit != EINSUMS_COMMIT:
            raise ValueError("Einsums runtime requires the pinned v1.1.5 source")
        if config.equivalence.policy_version != self.POLICY_VERSION:
            raise ValueError(f"Einsums requires equivalence policy {self.POLICY_VERSION}")
        self.config = replace(
            config, provider=replace(config.provider, name=provider_name or config.provider.name)
        )
        if self.config.provider.name not in ("offline", "openai"):
            raise ValueError("Einsums supports offline or explicitly selected openai translation")
        self.root = root
        self.run_id = (
            datetime.now(UTC).strftime("%Y%m%dT%H%M%S.%fZ") + "-" + self.config.sha256[:10]
        )
        self.run_dir = (root / config.runs_dir / self.run_id).resolve()
        for folder in (
            "source",
            "prompts",
            "translation",
            "builds",
            "corpus/seeds",
            "corpus/generated",
            "executions",
            "discrepancies",
            "traces",
        ):
            (self.run_dir / folder).mkdir(parents=True)
        self.events = self.run_dir / "provenance.jsonl"
        self.image = config.symsan.image
        self.cpp_binary = self.run_dir / "builds/native/einsums-reference"
        self.symsan_binary = self.run_dir / "builds/einsums-symsan"
        self.rust_binary: Path | None = None
        self.policy = TensorPolicy(
            config.equivalence.atol,
            config.equivalence.rtol,
            config.equivalence.signed_zero_equal,
            candidate_label=self.CANDIDATE_LABEL,
        )
        self.prompt = root / "prompts" / f"{config.provider.prompt_version}.txt"
        env = environment_record()
        commit = subprocess.run(
            ["git", "-C", str(root), "rev-parse", "HEAD"],
            capture_output=True,
            text=True,
            check=False,
        )
        self.manifest = RunManifest(
            "1.1",
            self.run_id,
            utc_now(),
            None,
            "IN_PROGRESS",
            {
                "sage": commit.stdout.strip() or "uncommitted-worktree",
                "einsums": EINSUMS_COMMIT,
                "symsan": config.symsan.upstream_commit,
            },
            self.config.sha256,
            {config.provider.prompt_version: sha256_file(self.prompt)},
            {"name": self.config.provider.name},
            env["tools"],
            {"symsan": self.image},
            [],
            config.equivalence.policy_version,
            test_counts_by_origin={"symsan": 0},
            known_limitations=self.LIMITATIONS,
            target_candidate="einsums",
            run_mode=run_mode,
            selection_decision=jsonable(selection) if selection is not None else None,
        )
        dump_config(self.config, self.run_dir / "config.resolved.yaml")
        write_json(self.run_dir / "environment.json", env)
        shutil.copy2(self.prompt, self.run_dir / "prompts" / self.prompt.name)
        self._save()

    def _save(self) -> None:
        write_json(self.run_dir / "manifest.json", self.manifest)

    def _docker(
        self,
        args: list[str],
        *,
        mount: str = "builds",
        destination: str = "/work",
        readonly: bool = False,
    ) -> list[str]:
        return [
            "docker",
            "run",
            "--rm",
            "--platform",
            "linux/amd64",
            "--network",
            "none",
            "--memory",
            f"{self.config.symsan.max_memory_mb}m",
            "--cpus",
            "1",
            "--pids-limit",
            "128",
            "-v",
            f"{self.run_dir / mount}:{destination}" + (":ro" if readonly else ""),
            "--entrypoint",
            "",
            self.image,
            *args,
        ]

    def _command(self, args: list[str], log: Path, timeout: int = 300) -> bool:
        try:
            completed = subprocess.run(
                args, capture_output=True, text=True, timeout=timeout, check=False
            )
            output = completed.stdout + completed.stderr
            success = completed.returncode == 0
        except (OSError, subprocess.TimeoutExpired) as exc:
            output = f"{type(exc).__name__}: command unavailable or timed out"
            success = False
        log.write_text("$ " + " ".join(args) + "\n" + output, encoding="utf-8")
        record_event(
            self.events,
            "command",
            {"command": args, "success": success, "log": str(log.relative_to(self.run_dir))},
        )
        return success

    def _pin_image(self) -> None:
        image_id = subprocess.check_output(
            ["docker", "image", "inspect", "--format", "{{.Id}}", self.image], text=True, timeout=15
        ).strip()
        self.image = image_id
        actual = subprocess.check_output(
            self._docker(["git", "-C", "/opt/einsums-src", "rev-parse", "HEAD"]),
            text=True,
            timeout=15,
        ).strip()
        dirty = subprocess.check_output(
            self._docker(["git", "-C", "/opt/einsums-src", "status", "--porcelain"]),
            text=True,
            timeout=15,
        ).strip()
        if actual != EINSUMS_COMMIT or dirty:
            raise ValueError("Einsums container source does not match the clean pinned revision")
        self.manifest.container_images["einsums_resolved"] = image_id
        self._save()

    def translate(self) -> Path:
        assert self.config.target is not None
        destination = self.root / ".sage/upstreams/einsums" / EINSUMS_COMMIT
        if not (destination / "checkout").is_dir():
            raise ValueError("prepare the source first: sage target prepare --target einsums")
        EinsumsTargetAdapter().prepare(self.config, destination)
        source = self.run_dir / "source"
        checkout = destination / "checkout"
        # Preserve the exact upstream tree for inspection without copying its Git database.
        snapshot = source / "upstream"
        if not snapshot.exists():
            shutil.copytree(checkout, snapshot, ignore=shutil.ignore_patterns(".git"))
        shutil.copy2(checkout / "LICENSE.txt", source / "EINSUMS-LICENSE.txt")
        shutil.copy2(self.root / "fixtures/einsums/driver.cpp", source / "driver.cpp")
        parts = [source / "driver.cpp", *(snapshot / path for path in SOURCE_FILES)]
        source_code = "\n\n".join(
            "// " + str(p.relative_to(source)) + "\n" + p.read_text() for p in parts
        )
        write_json(
            source / "hashes.json",
            {
                str(p.relative_to(source)): sha256_file(p)
                for p in snapshot.rglob("*")
                if p.is_file()
            },
        )
        request = TranslationRequest(
            "1.0",
            TranslationUnit(
                "1.0",
                "einsums-cpu-tensor-stage-1",
                str(source),
                sha256_bytes(source_code.encode()),
                list(OPERATIONS),
            ),
            source_code,
            self.prompt.read_text(),
            self.config.provider.prompt_version,
        )
        if self.config.provider.name == "openai":
            result = OpenAITranslationProvider(
                timeout_seconds=self.config.provider.timeout_seconds,
                max_retries=self.config.provider.max_retries,
            ).translate(request)
        else:
            fixture = self.root / "fixtures/translations/einsums_tensor.rs"
            code = fixture.read_text()
            result = TranslationResult(
                "1.0",
                "offline",
                code,
                {
                    "fixture": str(fixture),
                    "deterministic": True,
                    "operations": list(OPERATIONS),
                    "source_sha256": request.unit.source_sha256,
                    "scope": "bounded-cpu-tensors",
                    "target_language": "rust",
                },
                sha256_bytes(code.encode()),
            )
        candidate = self.run_dir / "translation/candidate.rs"
        candidate.write_text(result.code)
        write_json(candidate.with_suffix(".metadata.json"), result)
        self.manifest.translation_provider = {
            "name": result.provider,
            "metadata": result.metadata,
            "response_sha256": result.response_sha256,
        }
        self._save()
        return candidate

    def _build_reference(self) -> bool:
        build = self.run_dir / "builds"
        for filename in self.BUILD_FILES:
            shutil.copy2(self.root / self.FIXTURE_DIR / filename, build / filename)
        commands = [
            [
                "cmake",
                "-S",
                "/work",
                "-B",
                "/work/native",
                "-G",
                "Ninja",
                "-DCMAKE_CXX_COMPILER=clang++-18",
                "-DCMAKE_C_COMPILER=clang-18",
                "-DCMAKE_PREFIX_PATH=/opt/einsums",
                "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON",
            ],
            ["cmake", "--build", "/work/native", "--parallel", "1"],
            ["python3", "/work/build_symsan.py"],
        ]
        for index, args in enumerate(commands):
            if not self._command(self._docker(args), build / f"cpp-{index}.log"):
                return False
        self.manifest.build_records["c_reference"] = {
            "implementation": "einsums-upstream-cpp",
            "binary_sha256": sha256_file(self.cpp_binary),
            "instrumentation": "none",
            "image": self.image,
        }
        self.manifest.build_records["symsan_reference"] = {
            "implementation": self.INSTRUMENTATION,
            "binary_sha256": sha256_file(self.symsan_binary),
            "image": self.image,
            "metadata": json.loads((build / "instrumentation.json").read_text()),
        }
        self._save()
        return True

    def generate_tests(
        self, symsan_binary: Path | None = None
    ) -> tuple[list[TensorCase], SymSanGenerator]:
        if symsan_binary is None and self.config.symsan.enabled:
            self._pin_image()
            if self._build_reference():
                symsan_binary = self.symsan_binary
        seed_paths = []
        for seed in self.seeds():
            path = self.run_dir / "corpus/seeds" / f"{seed.case_id}.bin"
            path.write_bytes(seed.payload)
            write_json(path.with_suffix(".json"), seed.to_dict())
            seed_paths.append(path)
        generator = SymSanGenerator(
            replace(self.config.symsan, image=self.image),
            self.run_dir / "traces",
            seed_paths,
            symsan_binary,
            self.run_dir,
            decoder=self.CASE_TYPE.from_binary,
        )
        cases = cast(list[TensorCase], generator.generate())
        for case in cases:
            path = self.run_dir / "corpus/generated" / f"{case.case_id}.bin"
            path.write_bytes(case.payload)
            write_json(path.with_suffix(".json"), case.to_dict())
        self.manifest.test_counts_by_origin = {"symsan": len(cases)}
        self.manifest.concolic_outcome = generator.outcome
        self._save()
        return cases, generator

    def _execute(
        self, case: TensorCase, input_path: Path
    ) -> tuple[list[ExecutionResult], ComparisonResult]:
        assert self.rust_binary is not None
        started = time.monotonic()
        command = self._docker(
            [
                "/run/builds/native/einsums-reference",
                "/run/" + str(input_path.relative_to(self.run_dir)),
            ],
            mount="",
            destination="/run",
            readonly=True,
        )
        container_name = f"sage-case-{uuid.uuid4().hex}"
        command[3:3] = ["--name", container_name]
        try:
            completed = subprocess.run(
                command,
                capture_output=True,
                text=True,
                timeout=self.config.execution.timeout_seconds,
                check=False,
            )
            outputs = None
            code = completed.returncode
            stderr = completed.stderr
            if code == 0:
                try:
                    outputs = json.loads(completed.stdout)
                    if not isinstance(outputs, dict):
                        raise ValueError("expected JSON object")
                except ValueError:
                    code = 70
                    stderr += "\nrunner protocol failure: expected one JSON object"
            cpp = ExecutionResult(
                "1.0",
                "einsums-upstream-cpp",
                case.case_id,
                code,
                time.monotonic() - started,
                False,
                completed.stdout,
                stderr,
                outputs,
                {},
            )
        except subprocess.TimeoutExpired:
            # Killing the Docker CLI does not stop its daemon-owned container.
            with contextlib.suppress(OSError, subprocess.TimeoutExpired):
                subprocess.run(
                    ["docker", "rm", "-f", container_name],
                    capture_output=True,
                    timeout=15,
                    check=False,
                )
            cpp = ExecutionResult(
                "1.0",
                "einsums-upstream-cpp",
                case.case_id,
                None,
                time.monotonic() - started,
                True,
                "",
                "timeout",
                None,
                {},
            )
        except (OSError, ValueError):
            cpp = ExecutionResult(
                "1.0",
                "einsums-upstream-cpp",
                case.case_id,
                70,
                time.monotonic() - started,
                False,
                "",
                "runner protocol failure",
                None,
                {},
            )
        rust = SandboxedRunner(
            self.config.execution.timeout_seconds, self.config.execution.max_memory_mb
        ).execute(self.CANDIDATE_NAME, self.rust_binary, input_path, case.case_id)
        oracle = ExecutionResult(
            "1.0", "numpy", case.case_id, 0, 0, False, "", "", case.reference(), {}
        )
        return [cpp, rust, oracle], self.policy.compare(case, cpp, rust)

    def _discrepancy(
        self, case: TensorCase, input_path: Path, comparison: ComparisonResult
    ) -> None:
        executions, replay = self._execute(case, input_path)
        directory = self.run_dir / "discrepancies" / case.case_id
        directory.mkdir()
        shutil.copy2(input_path, directory / "input.bin")
        write_json(directory / "input.json", case.to_dict())
        write_json(directory / "replay.json", {"executions": executions, "comparison": replay})
        write_json(
            directory / "discrepancy.json",
            {
                "case_id": case.case_id,
                "outcome": comparison.outcome.value,
                "comparison": comparison,
                "replay_confirmed": replay.outcome == comparison.outcome,
            },
        )
        (directory / "README.md").write_text(f"Replay with `sage reproduce {directory}`.\n")

    def run(self) -> Path:
        comparisons: list[dict[str, Any]] = []
        try:
            if not self.config.symsan.enabled or self.config.symsan.trace_only:
                self.manifest.status = "UNSUPPORTED"
                self.manifest.concolic_outcome = {
                    "status": "UNSUPPORTED",
                    "generated": 0,
                    "reason": "SymSan-only validation requires enabled solver generation",
                }
                return self._finish(comparisons)
            self._pin_image()
            candidate = self.translate()
            if not self._build_reference():
                self.manifest.status = "BUILD_FAILURE"
                return self._finish(comparisons)
            rust = self._build_candidate(candidate)
            self.manifest.build_records[self.CANDIDATE_BUILD_KEY] = jsonable(rust)
            if not rust.success or rust.binary is None:
                self.manifest.status = "BUILD_FAILURE"
                return self._finish(comparisons)
            self.rust_binary = rust.binary
            cases, generator = self.generate_tests(self.symsan_binary)
            counts: collections.Counter[str] = collections.Counter()
            operations: collections.Counter[str] = collections.Counter()
            for case in cases:
                path = self.run_dir / "corpus/generated" / f"{case.case_id}.bin"
                executions, comparison = self._execute(case, path)
                write_json(self.run_dir / "executions" / f"{case.case_id}.json", executions)
                append_jsonl(self.run_dir / "comparisons.jsonl", comparison)
                comparisons.append(jsonable(comparison))
                counts[comparison.outcome.value] += 1
                operations[case.operation] += 1
                if comparison.outcome != Outcome.PASS:
                    self._discrepancy(case, path, comparison)
            self.manifest.outcome_counts = dict(counts)
            write_json(
                self.run_dir / "operation-coverage.json",
                {op: operations[op] for op in self.OPERATIONS},
            )
            self.manifest.concolic_outcome["operations"] = {
                op: operations[op] for op in self.OPERATIONS
            }
            status = generator.outcome["status"]
            if status != "COMPLETED":
                self.manifest.status = str(status)
            elif not cases:
                self.manifest.status = "NO_TEST_CASES"
            elif any(name != "PASS" for name in counts):
                self.manifest.status = "COMPLETED_WITH_DISCREPANCIES"
            else:
                self.manifest.status = "COMPLETED"
            return self._finish(comparisons)
        except (OSError, subprocess.SubprocessError, ValueError, RuntimeError) as exc:
            self.manifest.status = "INFRASTRUCTURE_FAILURE"
            write_json(
                self.run_dir / "error.json", {"type": type(exc).__name__, "message": str(exc)}
            )
            return self._finish(comparisons)

    def _build_rust(self, candidate: Path) -> Any:
        return RustCandidateBuilder(binary_name="einsums-rust-candidate").build(
            candidate, self.run_dir / "builds/rust"
        )

    def _build_candidate(self, candidate: Path) -> Any:
        return self._build_rust(candidate)

    def _finish(self, comparisons: list[dict[str, Any]]) -> Path:
        self.manifest.completed_at = utc_now()
        self._save()
        advisory = OfflineSummarizer().summarize({"outcomes": self.manifest.outcome_counts})
        write_json(self.run_dir / "advisory-summary.json", advisory)
        markdown = render_markdown(jsonable(self.manifest), comparisons, advisory)
        (self.run_dir / "report.md").write_text(markdown)
        write_html(self.run_dir / "report.html", markdown)
        record_event(self.events, "run-completed", {"status": self.manifest.status})
        return self.run_dir


def reproduce(discrepancy: Path) -> dict[str, str]:
    from sage.config import load_config

    run_dir = discrepancy.parent.parent
    config = load_config(run_dir / "config.resolved.yaml")
    # Replay recorded executables and the immutable image ID; never create a new campaign.
    runtime_class: type[EinsumsRun] = EinsumsRun
    if config.provider.target_language == "cpp20":
        from sage.einsums.cpp_runtime import EinsumsCppRun

        runtime_class = EinsumsCppRun
    if config.equivalence.policy_version == "einsums-library-1.0":
        from sage.einsums.library_runtime import EinsumsLibraryRun

        runtime_class = EinsumsLibraryRun
    runtime = object.__new__(runtime_class)
    runtime.config = config
    runtime.run_dir = run_dir
    manifest = json.loads((run_dir / "manifest.json").read_text())
    runtime.image = manifest["container_images"]["einsums_resolved"]
    runtime.rust_binary = Path(manifest["build_records"][runtime.CANDIDATE_BUILD_KEY]["binary"])
    if config.equivalence.policy_version == "einsums-library-1.0":
        runtime.python_library = Path(  # type: ignore[attr-defined]
            manifest["build_records"]["rust_candidate"]["metadata"]["python_library"]
        )
    runtime.policy = TensorPolicy(
        config.equivalence.atol,
        config.equivalence.rtol,
        config.equivalence.signed_zero_equal,
        candidate_label=runtime.CANDIDATE_LABEL,
    )
    case = runtime.CASE_TYPE.from_binary((discrepancy / "input.bin").read_bytes(), discrepancy.name)
    executions, comparison = runtime._execute(case, discrepancy / "input.bin")
    write_json(
        discrepancy / "manual-replay.json", {"executions": executions, "comparison": comparison}
    )
    return {"case_id": case.case_id, "outcome": comparison.outcome.value}
