"""Validate the current CPU Python API using only an authenticated SymSan corpus.

This is a deterministic operation/dtype sweep over existing generated bytes,
not a claim that SymSan explored any newly added numerical implementation.
"""

from __future__ import annotations

import argparse
import collections
import datetime
import hashlib
import json
import os
import shutil
import subprocess
import sys
import uuid
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
OPERATIONS = [
    "tensor",
    "gemm",
    "gemv",
    "scale",
    "scale_row",
    "scale_column",
    "dot",
    "true_dot",
    "axpy",
    "axpby",
    "ger",
    "direct_product",
    "norm",
    "vec_norm",
    "sum_square",
    "lu",
    "invert",
    "gesv",
    "det",
    "syev",
    "heev",
    "geev",
    "svd",
    "svd_dd",
    "svd_nullspace",
    "qr",
    "pseudoinverse",
    "solve_continuous_lyapunov",
    "truncated_svd",
    "truncated_syev",
    "plan",
]


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def write(path, value):
    path.write_text(json.dumps(value, indent=2) + "\n")


def compare(record):
    if "error" in record:
        return False, record["error"]
    dtype = record["dtype"]
    low = dtype in ("float32", "complex64")
    atol, rtol = (2e-4, 5e-4) if low else (1e-8, 1e-8)
    if len(record["actual"]) != len(record["expected"]):
        return False, "output count differs"
    for i, (a, b) in enumerate(zip(record["actual"], record["expected"], strict=True)):
        if a["shape"] != b["shape"] or a["dtype"] != b["dtype"]:
            return (
                False,
                f"output {i} shape/dtype: {a['shape']}/{a['dtype']} != {b['shape']}/{b['dtype']}",
            )
        av = np.asarray(a["values"], dtype=float).reshape(-1, 2)
        bv = np.asarray(b["values"], dtype=float).reshape(-1, 2)
        az, bz = av[:, 0] + 1j * av[:, 1], bv[:, 0] + 1j * bv[:, 1]
        if not np.allclose(az, bz, rtol=rtol, atol=atol, equal_nan=False):
            return False, f"output {i} numerical disagreement"
    return True, ""


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run", type=Path, required=True, help="source SymSan run")
    parser.add_argument("--image", default="sage-einsums-python:22a1159")
    parser.add_argument("--language", choices=["rust", "cpp20"], default="rust")
    parser.add_argument("--operations", nargs="+", choices=OPERATIONS, default=OPERATIONS)
    args = parser.parse_args()
    source = args.run.resolve()
    stamp = datetime.datetime.now(datetime.UTC).strftime("%Y%m%dT%H%M%S.%fZ")
    output = (
        ROOT / "runs" / (stamp + "-einsums-api" + ("-cpp20" if args.language == "cpp20" else ""))
    )
    output.mkdir(parents=True)
    cases = []
    for path in sorted((source / "corpus/generated").glob("*.json")):
        if path.name.endswith(".invalid.json"):
            continue
        record = json.loads(path.read_text())
        if record.get("provenance", {}).get("origin") != "symsan":
            raise ValueError(f"non-SymSan input {path}")
        raw = path.with_suffix(".bin").read_bytes()
        generated = source / "corpus/generated" / Path(record["provenance"]["generated_file"]).name
        if raw.hex() != record["payload_hex"] or generated.read_bytes() != raw:
            raise ValueError(f"payload/provenance mismatch {path}")
        if len(raw) != 36 or any(n < 1 or n > 4 for n in raw[1:4]):
            raise ValueError("invalid input domain")
        cases.append(
            {
                "case_id": record["case_id"],
                "hex": raw.hex(),
                "sha256": digest(generated),
                "source": str(path.relative_to(source)),
                "metadata_sha256": digest(path),
            }
        )
    seeds = {p.read_bytes() for p in (source / "corpus/seeds").glob("*.bin")}
    if (
        not cases
        or len({c["hex"] for c in cases}) != len(cases)
        or any(bytes.fromhex(c["hex"]) in seeds for c in cases)
    ):
        raise ValueError("corpus must be nonempty, unique, generated, and exclude seeds")
    write(output / "corpus.json", cases)
    image = subprocess.check_output(
        ["docker", "image", "inspect", "--format", "{{.Id}}", args.image], text=True
    ).strip()
    cpp = args.language == "cpp20"
    port = ROOT / "ports" / ("einsums-cpp" if cpp else "einsums-rs")
    candidate_name = "cpp20_python" if cpp else "rust_python"
    candidate = output / "translation" / port.name
    shutil.copytree(
        port,
        candidate,
        ignore=shutil.ignore_patterns(
            "target", "build", "build-*", "__pycache__", "dist", "_native"
        ),
    )
    # Build once in the workspace, then copy and hash the exact artifact used by this run.
    build_command = [
        "cargo",
        "build",
        "--locked",
        "--offline",
        "--manifest-path",
        str(port / "Cargo.toml"),
    ]
    with (output / "build.log").open("w") as log:
        if cpp:
            configure = [
                "cmake",
                "-S",
                str(candidate),
                "-B",
                str(output / "build"),
                "-DCMAKE_BUILD_TYPE=Release",
                "-DBUILD_TESTING=OFF",
            ]
            subprocess.run(configure, stdout=log, stderr=log, check=True)
            build_command = ["cmake", "--build", str(output / "build"), "-j", "2"]
        subprocess.run(build_command, stdout=log, stderr=log, check=True)
    libname = ("libsage_einsums_cpp" if cpp else "libsage_einsums") + (
        ".dylib" if sys.platform == "darwin" else ".so"
    )
    library = output / libname
    shutil.copy2((output / "build" if cpp else port / "target/debug") / libname, library)
    replay = output / "replay.py"
    shutil.copy2(ROOT / "fixtures/einsums-api/replay.py", replay)
    shutil.copy2(Path(__file__), output / "validate_einsums_api.py")
    manifest = {
        "schema_version": "einsums-api-replay-1.0",
        "target_language": args.language,
        "source_run": str(source),
        "source_manifest_sha256": digest(source / "manifest.json"),
        "reference_image": image,
        "candidate_library_sha256": digest(library),
        "build_command": build_command,
        "candidate_files": {
            str(p.relative_to(candidate)): digest(p) for p in candidate.rglob("*") if p.is_file()
        },
        "replay_sha256": digest(replay),
        "corpus_sha256": digest(output / "corpus.json"),
        "generated_inputs": len(cases),
        "operations": args.operations,
        "dtypes": ["float32", "float64", "complex64", "complex128"],
        "generation": (
            "Reused authenticated SymSan bytes; fixed API/dtype sweeps are not new generated cases."
        ),
        "instrumentation": (
            "Input decoder only in source run; no internal library branch exploration."
        ),
        "policy": {
            "f32_c64": {"atol": 2e-4, "rtol": 5e-4},
            "f64_c128": {"atol": 1e-8, "rtol": 1e-8},
            "basis_comparison": (
                "normalized residuals and orthogonality, not individual nonunique basis vectors"
            ),
            "truncation": "8x8 arrays deterministically resized from generated values; k=1",
        },
    }
    write(output / "manifest.json", manifest)
    records = {}
    execution = []
    for op in args.operations:
        for implementation in ("original", candidate_name):
            env = dict(os.environ)
            name = "sage-api-" + uuid.uuid4().hex
            if implementation == "original":
                command = [
                    "docker",
                    "run",
                    "--rm",
                    "--name",
                    name,
                    "--platform",
                    "linux/amd64",
                    "--network",
                    "none",
                    "--memory",
                    "2g",
                    "--cpus",
                    "1",
                    "--pids-limit",
                    "128",
                    "-e",
                    "OPENBLAS_NUM_THREADS=1",
                    "-e",
                    "OMP_NUM_THREADS=1",
                    "-v",
                    f"{output}:/audit:ro",
                    "--entrypoint",
                    "python3",
                    image,
                    "/audit/replay.py",
                    "/audit/corpus.json",
                    op,
                ]
            else:
                env.update(
                    PYTHONPATH=str(candidate / "python"),
                    OPENBLAS_NUM_THREADS="1",
                )
                env["EINSUMS_CPP_LIBRARY" if cpp else "EINSUMS_RS_LIBRARY"] = str(library)
                command = [sys.executable, str(replay), str(output / "corpus.json"), op]
            out = output / f"{implementation}-{op}.jsonl"
            err = output / f"{implementation}-{op}.stderr"
            with out.open("w") as stdout, err.open("w") as stderr:
                try:
                    completed = subprocess.run(
                        command, env=env, stdout=stdout, stderr=stderr, timeout=180, check=False
                    )
                    returncode = completed.returncode
                except subprocess.TimeoutExpired:
                    returncode = 124
                    if implementation == "original":
                        subprocess.run(
                            ["docker", "rm", "-f", name], capture_output=True, check=False
                        )
            execution.append(
                {
                    "implementation": implementation,
                    "operation": op,
                    "returncode": returncode,
                    "command": command,
                }
            )
            count = 0
            for line in out.read_text().splitlines():
                try:
                    item = json.loads(line)
                except ValueError:
                    continue  # Native logging is preserved verbatim in the raw output.
                if not isinstance(item, dict) or "case_id" not in item:
                    continue
                passed, message = compare(item)
                key = (item["case_id"], op, item["dtype"])
                records.setdefault(key, {})[implementation] = {"passed": passed, "message": message}
                count += 1
            print(
                f"{op}: {implementation} {count}/{len(cases) * 4} records, exit {returncode}",
                flush=True,
            )
    counts = collections.Counter()
    comparisons = []
    for case in cases:
        for op in args.operations:
            for dtype in manifest["dtypes"]:
                key = (case["case_id"], op, dtype)
                pair = records.get(key, {})
                original, candidate_result = pair.get("original"), pair.get(candidate_name)
                if original is None or candidate_result is None:
                    status = "EXECUTION_FAILURE"
                elif original["passed"] and candidate_result["passed"]:
                    status = "PASS"
                elif not candidate_result["passed"]:
                    status = "CANDIDATE_DISAGREEMENT"
                else:
                    status = "REFERENCE_DISAGREEMENT"
                counts[status] += 1
                comparisons.append(
                    {"case_id": key[0], "operation": op, "dtype": dtype, "outcome": status, **pair}
                )
    with (output / "comparisons.jsonl").open("w") as f:
        for item in comparisons:
            f.write(json.dumps(item) + "\n")
    write(output / "executions.json", execution)
    manifest.update(
        outcomes=dict(counts), status="PASS" if set(counts) == {"PASS"} else "DISCREPANCIES"
    )
    write(output / "manifest.json", manifest)
    lines = [
        "# Einsums CPU API replay",
        "",
        f"Generated inputs: {len(cases)}. API/dtype checks: {len(comparisons)}.",
        "",
        (
            "Every input is an authenticated SymSan-generated payload, "
            "replayed against the compiled pinned C++ Python extension and the"
            f" independent {args.language}-backed Python package. Both are checked against"
            " NumPy values or numerical residuals."
        ),
        "",
        "| Outcome | Checks |",
        "|---|---:|",
    ]
    lines.extend(f"| {key} | {value} |" for key, value in sorted(counts.items()))
    lines += [
        "",
        (
            "These are operation/dtype sweeps of the saved corpus, not new "
            f"concolic path discoveries. Python replay exercises the {args.language} C "
            "ABI; it does not separately validate every direct native "
            "entrypoint. HDF5, decomposition and runtime service tests are "
            "separate implementation checks. Passing this finite corpus does "
            "not establish whole-library equivalence."
        ),
        "",
        (
            "See manifest.json, executions.json, comparisons.jsonl and per-"
            "operation raw outputs for provenance and discrepancies."
        ),
    ]
    (output / "report.md").write_text("\n".join(lines) + "\n")
    print(output, flush=True)
    print(dict(counts), flush=True)
    return 0 if manifest["status"] == "PASS" else 1


if __name__ == "__main__":
    raise SystemExit(main())
